frontend:
build: frontend 
command: "-Dconfig.file=/etc/opt/frontend/docker.conf" 
links:
- "service"
ports:
- "49910:9000"
# volumes:
# - frontend/conf:/etc/opt/frontend:ro
volumes_from:
- maven
service:
build: service 
command: run -Dconfig.file=/etc/opt/service/docker.conf 
links:
- "database"
ports:
- "49920:8880"
expose:
- "8880"
# volumes:
# - service/src/main/resources:/etc/opt/service:ro
volumes_from:
- maven
database:
image: postgres:9.4 
expose:
- "5432"
maven:
image: debian:wheezy 
volumes:
- ~/.m2:/root/.m2: 
- ~/.ivy2:/root/.ivy2:rw 
- ~/.m2:/home/docker/.ivy2:rw 
- ~/.ivy2:/home/docker/.ivy2:rw 
- services/src/main/resources:/root/.sbt:ro