-- COMMENT TABLE START --
DROP TABLE IF EXISTS COMMENT;
CREATE TABLE IF NOT EXISTS COMMENT (
    ID INT(10) NOT NULL AUTO_INCREMENT,
    COMMENT_DATE date NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    EMAIL_ID VARCHAR(40) NOT NULL,
    ROLE_LEVEL_ID INT(10) NOT NULL,
    PRIMARY KEY (ID),
    KEY PERSON_ROLE_LEVEL_FK (ROLE_LEVEL_ID),
    CONSTRAINT PERSON_ROLE_LEVEL_FK FOREIGN KEY  (ROLE_LEVEL_ID) REFERENCES ROLELEVEL(ID)
);
-- COMMENT TABLE END --